name: Deploy Web App - hport

on:
  push:
    branches:
      - main
    paths:
      - 'hport-web/**'
      - '.github/workflows/deploy-web-app.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Create and Start virtual environment and Install dependencies
        run: |
          cd hport-web
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            hport-web/
            !hport-web/antenv/
            !hport-web/__pycache__/
            !hport-web/*.pyc
            !hport-web/.env
            !hport-web/.venv/
            !hport-web/tests/
            !hport-web/.pytest_cache/
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_943AB9994AF34F4583ADB5C6455BBF52 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FC3E4E91DA57491F8009326BB4867E37 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E0045ED15B04469E998ED34DE897C096 }}
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'hport'
          slot-name: 'Production'
          package: './hport-web'
