name: Deploy Function App

on:
  push:
    branches:
      - main
    paths:
      - 'function-app/**'
      - '.github/workflows/deploy-function-app.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'function-app'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../function-app.zip . -x ".venv/*" "__pycache__/*" "*.pyc" ".pytest_cache/*" "tests/*" "local.settings.json"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: function-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: function-app

      - name: Unzip artifact for deployment
        run: unzip function-app.zip -d function-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_FUNCTIONAPP_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_FUNCTIONAPP_TENANTID }}
          subscription-id: ${{ secrets.AZURE_FUNCTIONAPP_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'YOUR_FUNCTION_APP_NAME'
          package: './function-app'
          scm-do-build-during-deployment: true
          enable-oryx-build: true
